on: push
jobs:
    buid-node: 
        runs-on: ubuntu-latest
        container: python
        steps:
            - run: python --version
            - uses: actions/checkout@v3
            - run: python helloworld.py
